services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app_network
  server:
    build:
      context: .
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    name: app

volumes:
  postgresql_data: