# Generated by Django 5.1.3 on 2024-11-29 18:13

from django.db import migrations


def add_initial_data(apps, schema_editor):
    # Get models
    restaurant_model = apps.get_model("online_delivery", "Restaurant")
    product_category_model = apps.get_model("online_delivery", "ProductCategory")
    product_model = apps.get_model("online_delivery", "Product")

    # Add restaurants
    restaurants = [
        restaurant_model.objects.create(
            name="Gourmet Kitchen",
            description="Fine dining restaurant",
            address="123 Fancy St",
        ),
        restaurant_model.objects.create(
            name="Fast Foodies", description="Quick bites", address="456 Burger Ave"
        ),
        restaurant_model.objects.create(
            name="Vegan Delights",
            description="Healthy vegan options",
            address="789 Green Rd",
        ),
    ]

    # Add product categories

    categories_data = [
        {
            "name": "Beverages",
            "description": "A wide variety of drinks to quench your thirst and delight your taste buds,"
            " including soft drinks, juices, teas, coffees, and smoothies.",
        },
        {
            "name": "Appetizers",
            "description": "Start your meal with a treat for your taste buds and tummy,"
            " featuring a selection of small dishes like nachos, spring rolls, and bruschetta.",
        },
        {
            "name": "Main Courses",
            "description": "Hearty and fulfilling dishes to satisfy your hunger and cravings, including grilled meats,"
            " pasta, seafood, and vegetarian options.",
        },
        {
            "name": "Desserts",
            "description": "Sweet indulgences to end your meal on a high note, with options like chocolate cake,"
            " cheesecake, ice cream, and fruit tarts.",
        },
        {
            "name": "Salads",
            "description": "Fresh and healthy combinations of vegetables, fruits, and proteins, perfect for a light"
            " meal or a side dish.",
        },
        {
            "name": "Soups",
            "description": "Warm and comforting bowls of goodness, ranging from classic tomato soup to hearty beef"
            " stew and exotic miso soup.",
        },
        {
            "name": "Side Dishes",
            "description": "Perfect complements to your main course, including mashed potatoes, french fries,"
            " grilled vegetables, and more.",
        },
        {
            "name": "Sandwiches",
            "description": "Convenient and satisfying options for a quick meal, featuring a variety of fillings "
            "like club sandwiches, BLTs, and grilled cheese.",
        },
        {
            "name": "Seafood",
            "description": "Delicacies from the sea, including grilled shrimp, crab cakes, lobster tail, "
            "and sushi rolls.",
        },
        {
            "name": "Vegetarian",
            "description": "Delicious plant-based meals that are both nutritious and flavorful, such as "
            "vegetable stir-fry, vegetarian curry, and veggie burgers.",
        },
    ]

    categories = [
        product_category_model.objects.create(**category)
        for category in categories_data
    ]

    # Add products
    products_data = {
        "Beverages": [
            {
                "name": "Cola",
                "description": "Carbonated soft drink",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Orange Juice",
                "description": "Freshly squeezed",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lemonade",
                "description": "Refreshing lemon drink",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Iced Tea",
                "description": "Chilled, with lemon flavor",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Coffee",
                "description": "Brewed hot beverage",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Green Tea",
                "description": "Healthy green tea",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Smoothie",
                "description": "Fruit blend drink",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Milkshake",
                "description": "Ice cream-based shake",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Hot Chocolate",
                "description": "Warm chocolate drink",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mojito",
                "description": "Minty lemon drink",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Latte",
                "description": "Steamed milk with espresso",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Espresso",
                "description": "Strong coffee shot",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Herbal Tea",
                "description": "Assorted herbal infusions",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Mineral Water",
                "description": "Natural spring water",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Energy Drink",
                "description": "Boosting beverage",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Appetizers": [
            {
                "name": "Nachos",
                "description": "Corn chips with cheese",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Spring Rolls",
                "description": "Vegetable rolls",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Bruschetta",
                "description": "Tomato basil topping",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Stuffed Mushrooms",
                "description": "Cheesy stuffed mushrooms",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Garlic Bread",
                "description": "Garlic toasted bread",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Chicken Wings",
                "description": "Spicy crispy wings",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Shrimp Cocktail",
                "description": "Chilled shrimp with sauce",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Potato Skins",
                "description": "Loaded potato skins",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Fried Calamari",
                "description": "Crispy squid rings",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Deviled Eggs",
                "description": "Stuffed eggs",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Caprese Salad",
                "description": "Tomato mozzarella salad",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Hummus",
                "description": "Chickpea dip",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Guacamole",
                "description": "Avocado dip",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Quesadillas",
                "description": "Cheese stuffed tortillas",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Cheese Platter",
                "description": "Assorted cheese selection",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Main Courses": [
            {
                "name": "Grilled Chicken",
                "description": "Marinated grilled chicken",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Beef Steak",
                "description": "Juicy grilled steak",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Spaghetti Carbonara",
                "description": "Pasta with creamy sauce",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Salmon Fillet",
                "description": "Grilled salmon with herbs",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Vegetarian Pizza",
                "description": "Pizza with veg toppings",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lamb Chops",
                "description": "Grilled lamb ribs",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Chicken Alfredo",
                "description": "Creamy pasta with chicken",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Tofu Stir-fry",
                "description": "Stir-fried tofu with veggies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Beef Tacos",
                "description": "Gluten beef tacos",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Vegan Burger",
                "description": "Plant-based patty",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Lasagna",
                "description": "Layered pasta dish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Chicken Curry",
                "description": "Spicy Indian curry",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Ratatouille",
                "description": "Vegetable stew",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Fish and Chips",
                "description": "Battered fish with fries",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Shrimp Scampi",
                "description": "Shrimp with garlic butter",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Desserts": [
            {
                "name": "Chocolate Cake",
                "description": "Rich chocolate dessert",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Cheesecake",
                "description": "Creamy cheesecake",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Apple Pie",
                "description": "Classic apple pie",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Tiramisu",
                "description": "Italian coffee-flavored dessert",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Panna Cotta",
                "description": "Creamy Italian dessert",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Profiteroles",
                "description": "Puff pastry with cream",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Creme Brulee",
                "description": "Caramel custard dessert",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Brownie",
                "description": "Classic chocolate brownie",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Ice Cream",
                "description": "Assorted flavors",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mousse",
                "description": "Light and fluffy chocolate mousse",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Fruit Tart",
                "description": "Tart with seasonal fruits",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Macarons",
                "description": "French almond cookies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Trifle",
                "description": "Layered dessert with cream",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Lemon Meringue Pie",
                "description": "Tangy lemon pie",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Pavlova",
                "description": "Meringue-based dessert",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Salads": [
            {
                "name": "Caesar Salad",
                "description": "Crispy lettuce with Caesar dressing",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Greek Salad",
                "description": "Salad with feta and olives",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Caprese Salad",
                "description": "Tomato, mozzarella, and basil",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Cobb Salad",
                "description": "Mixed greens with eggs and bacon",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Waldorf Salad",
                "description": "Apples, nuts, and grapes",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Spinach Salad",
                "description": "Fresh spinach with bacon",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Quinoa Salad",
                "description": "Quinoa with veggies and lemon",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Asian Slaw",
                "description": "Crunchy cabbage with Asian dressing",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Kale Salad",
                "description": "Kale with cranberries and almonds",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Pasta Salad",
                "description": "Fusilli with mixed veggies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Broccoli Salad",
                "description": "Broccoli, bacon, and raisins",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Chickpea Salad",
                "description": "Chickpeas with herbs",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Tabbouleh",
                "description": "Parsley, bulgur, and tomato",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Avocado Salad",
                "description": "Avocado with lime dressing",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Fruit Salad",
                "description": "Fresh seasonal fruits",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Soups": [
            {
                "name": "Tomato Soup",
                "description": "Classic tomato soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Chicken Noodle Soup",
                "description": "Chicken broth with noodles",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Minestrone",
                "description": "Italian vegetable soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "French Onion Soup",
                "description": "Soup with caramelized onions",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Lentil Soup",
                "description": "Thick lentil-based soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Clam Chowder",
                "description": "Creamy seafood soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Miso Soup",
                "description": "Japanese fermented soy soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Pumpkin Soup",
                "description": "Creamy pumpkin soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Gazpacho",
                "description": "Cold Spanish tomato-based soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Carrot Ginger Soup",
                "description": "Spicy carrot and ginger soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Broccoli Cheddar Soup",
                "description": "Cheesy broccoli soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Beef Stew",
                "description": "Hearty beef and vegetable stew",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Split Pea Soup",
                "description": "Thick pea soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Turkey Soup",
                "description": "Soup with turkey leftovers",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Vichyssoise",
                "description": "Chilled leek and potato soup",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Side Dishes": [
            {
                "name": "Mashed Potatoes",
                "description": "Creamy mashed potatoes",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "French Fries",
                "description": "Crispy potato fries",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Onion Rings",
                "description": "Battered fried onions",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Coleslaw",
                "description": "Cabbage and carrot slaw",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Cornbread",
                "description": "Traditional cornbread",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Garlic Butter Potatoes",
                "description": "Roasted buttery potatoes",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Grilled Vegetables",
                "description": "Charred veggies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Rice Pilaf",
                "description": "Flavored rice dish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Baked Beans",
                "description": "Slow-cooked beans in sauce",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Roasted Brussels Sprouts",
                "description": "Roasted green sprouts",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Macaroni and Cheese",
                "description": "Creamy cheesy pasta",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Stuffing",
                "description": "Bread-based stuffing",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Potato Gratin",
                "description": "Layered potato dish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Steamed Asparagus",
                "description": "Tender green asparagus",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Sautéed Spinach",
                "description": "Lightly sautéed spinach",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Sandwiches": [
            {
                "name": "Club Sandwich",
                "description": "Three-layered sandwich",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "BLT",
                "description": "Bacon, lettuce, and tomato",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Grilled Cheese",
                "description": "Cheesy toasted bread",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Chicken Wrap",
                "description": "Chicken rolled in flatbread",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Reuben",
                "description": "Corned beef and sauerkraut",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Peanut Butter & Jelly",
                "description": "Classic sweet sandwich",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Turkey and Swiss",
                "description": "Turkey with Swiss cheese",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Egg Salad Sandwich",
                "description": "Egg salad and mustard",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Ham and Cheese",
                "description": "Ham with melted cheese",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Falafel Pita",
                "description": "Falafel balls in pita bread",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Tuna Melt",
                "description": "Tuna salad with melted cheese",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Vegan Wrap",
                "description": "Hummus and veggies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Cuban Sandwich",
                "description": "Ham, pork, and cheese",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Roast Beef Sandwich",
                "description": "Sliced beef and cheddar",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Caprese Sandwich",
                "description": "Mozzarella and tomato",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Seafood": [
            {
                "name": "Grilled Shrimp",
                "description": "Shrimp grilled to perfection",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Crab Cakes",
                "description": "Spiced cakes with fresh crab",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lobster Tail",
                "description": "Broiled lobster tail",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Fish Tacos",
                "description": "Crispy fish in tortillas",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Seafood Paella",
                "description": "Mixed seafood with rice",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Oysters on the Half Shell",
                "description": "Raw oysters served chilled",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mussels in White Wine Sauce",
                "description": "Mussels cooked in sauce",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Grilled Octopus",
                "description": "Tender grilled octopus",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Fried Fish",
                "description": "Battered and fried fish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Blackened Catfish",
                "description": "Spicy grilled catfish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Seafood Gumbo",
                "description": "Spicy seafood stew",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Baked Salmon",
                "description": "Oven-baked salmon fillet",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Sushi Rolls",
                "description": "Assorted sushi",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Tuna Sashimi",
                "description": "Fresh raw tuna slices",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Scampi",
                "description": "Garlic-butter prawns",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Vegetarian": [
            {
                "name": "Vegetable Stir-fry",
                "description": "Fresh veggies with sauce",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Vegetarian Curry",
                "description": "Mixed vegetable curry",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Veggie Burger",
                "description": "Grilled veggie patty",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mushroom Risotto",
                "description": "Creamy mushroom rice dish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Stuffed Bell Peppers",
                "description": "Pepper stuffed with quinoa",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Eggplant Parmesan",
                "description": "Layered eggplant dish",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Vegetable Lasagna",
                "description": "Lasagna with veggies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Chickpea Salad",
                "description": "Salad with spiced chickpeas",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Falafel",
                "description": "Spicy chickpea balls",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Veggie Tacos",
                "description": "Tacos with mixed veggies",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Paneer Butter Masala",
                "description": "Paneer in creamy sauce",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Spinach and Ricotta Ravioli",
                "description": "Stuffed pasta",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Vegetable Quesadillas",
                "description": "Cheese and veg filled tortillas",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Vegan Sushi",
                "description": "Sushi without seafood",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lentil Burgers",
                "description": "Burgers with lentil patty",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
    }

    for category in categories:
        product_list = products_data.get(category.name, [])
        for product_data in product_list:
            product_model.objects.create(
                name=product_data["name"],
                description=product_data["description"],
                category=category,
                restaurant=product_data["restaurant"],
                image=product_data["image"],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("online_delivery", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
