# Generated by Django 5.1.3 on 2024-12-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_delivery", "0002_mock_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="online_delivery.product",
            ),
        ),
    ]
