# Generated by Django 5.1.3 on 2024-11-29 18:13

from django.db import migrations


def add_initial_data(apps, schema_editor):
    # Get models
    restaurant_model = apps.get_model("online_delivery", "Restaurant")
    product_category_model = apps.get_model("online_delivery", "ProductCategory")
    product_model = apps.get_model("online_delivery", "Product")

    # Add restaurants
    restaurants = [
        restaurant_model.objects.create(
            name="Gourmet Kitchen",
            description="Fine dining restaurant",
            address="123 Fancy St",
        ),
        restaurant_model.objects.create(
            name="Fast Foodies", description="Quick bites", address="456 Burger Ave"
        ),
        restaurant_model.objects.create(
            name="Vegan Delights",
            description="Healthy vegan options",
            address="789 Green Rd",
        ),
    ]

    # Add product categories

    categories_data = [
        {
            "name": "Beverages",
            "image": "categories/Beverages.png",
            "description": "A wide variety of drinks to quench your thirst and delight your taste buds,"
            " including soft drinks, juices, teas, coffees, and smoothies.",
        },
        {
            "name": "Appetizers",
            "image": "categories/Appetizers.png",
            "description": "Start your meal with a treat for your taste buds and tummy,"
            " featuring a selection of small dishes like nachos, spring rolls, and bruschetta.",
        },
        {
            "name": "Main Courses",
            "image": "categories/Main Courses.png",
            "description": "Hearty and fulfilling dishes to satisfy your hunger and cravings, including grilled meats,"
            " pasta, seafood, and vegetarian options.",
        },
        {
            "name": "Desserts",
            "image": "categories/Desserts.png",
            "description": "Sweet indulgences to end your meal on a high note, with options like chocolate cake,"
            " cheesecake, ice cream, and fruit tarts.",
        },
        {
            "name": "Salads",
            "image": "categories/Salads.png",
            "description": "Fresh and healthy combinations of vegetables, fruits, and proteins, perfect for a light"
            " meal or a side dish.",
        },
        {
            "name": "Soups",
            "image": "categories/Soups.png",
            "description": "Warm and comforting bowls of goodness, ranging from classic tomato soup to hearty beef"
            " stew and exotic miso soup.",
        },
        {
            "name": "Side Dishes",
            "image": "categories/Side Dishes.png",
            "description": "Perfect complements to your main course, including mashed potatoes, french fries,"
            " grilled vegetables, and more.",
        },
        {
            "name": "Sandwiches",
            "image": "categories/Sandwiches.png",
            "description": "Convenient and satisfying options for a quick meal, featuring a variety of fillings "
            "like club sandwiches, BLTs, and grilled cheese.",
        },
        {
            "name": "Seafood",
            "image": "categories/Seafood.png",
            "description": "Delicacies from the sea, including grilled shrimp, crab cakes, lobster tail, "
            "and sushi rolls.",
        },
        {
            "name": "Vegetarian",
            "image": "categories/Vegetarian.png",
            "description": "Delicious plant-based meals that are both nutritious and flavorful, such as "
            "vegetable stir-fry, vegetarian curry, and veggie burgers.",
        },
    ]

    categories = [
        product_category_model.objects.create(**category)
        for category in categories_data
    ]

    # Add products
    products_data = {
        "Beverages": [
            {
                "name": "Cola",
                "description": "A classic and refreshing carbonated soft drink with just the right amount of sweetness and fizz to energize your day.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Orange Juice",
                "description": "Experience the vibrant taste of freshly squeezed oranges packed with vitamin C for a delightful and healthy refreshment.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lemonade",
                "description": "Quench your thirst with this classic drink, made with freshly squeezed lemons and a hint of sweetness for a perfectly refreshing taste.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Iced Tea",
                "description": "A chilled beverage infused with lemon flavor, offering a perfect balance of sweet and tangy for a cool, invigorating experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Coffee",
                "description": "Enjoy the rich and robust flavors of our freshly brewed hot coffee, perfect for a morning pick-me-up or an afternoon boost.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Green Tea",
                "description": "Savor the light and earthy flavors of our healthy green tea, known for its antioxidants and calming benefits.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Smoothie",
                "description": "A delicious and nutritious fruit blend smoothie, packed with vitamins and perfect as a refreshing snack or meal replacement.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Milkshake",
                "description": "An indulgent treat made from creamy ice cream blended to perfection, available in a variety of classic and fun flavors.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Hot Chocolate",
                "description": "Warm up with our rich and creamy hot chocolate, crafted with quality cocoa for a cozy and comforting experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mojito",
                "description": "A vibrant minty lemon drink, perfect for refreshing your senses with a hint of sweetness and a twist of lime.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Latte",
                "description": "Delight in the smooth and creamy flavors of steamed milk blended with rich espresso for a satisfying coffee experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Espresso",
                "description": "Indulge in a strong and invigorating shot of espresso, expertly brewed to deliver a bold and rich coffee experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Herbal Tea",
                "description": "Delight in a selection of assorted herbal infusions, each offering unique flavors and aromas for a soothing experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Mineral Water",
                "description": "Experience the crisp and pure taste of natural spring water, perfect for hydration and replenishment anytime.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Energy Drink",
                "description": "Boost your energy with our invigorating beverage, designed to provide immediate refreshment and sustained energy.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Appetizers": [
            {
                "name": "Nachos",
                "description": "Crisp corn tortilla chips generously topped with melted cheese, jalapeños, and fresh salsa for a perfect start to any meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Spring Rolls",
                "description": "Light and crispy rolls stuffed with a vibrant mix of fresh vegetables, served with a tangy dipping sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Bruschetta",
                "description": "Toasted bread topped with a fragrant mix of ripe tomatoes, fresh basil, and a drizzle of olive oil for a classic Italian treat.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Stuffed Mushrooms",
                "description": "Savory mushrooms filled with a creamy, cheesy stuffing and baked to golden perfection for a bite-sized delight.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Garlic Bread",
                "description": "Toasted slices of Italian bread slathered in garlic butter, offering a comforting and savory start to your meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Chicken Wings",
                "description": "Juicy chicken wings, marinated and cooked to crispy perfection, tossed in your choice of spicy or savory sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Shrimp Cocktail",
                "description": "Chilled shrimp served with a zesty cocktail sauce, offering a refreshing and sophisticated seafood appetizer.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Potato Skins",
                "description": "Crispy potato skins loaded with melted cheese, bacon bits, and scallions, served with a side of sour cream.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Fried Calamari",
                "description": "Lightly breaded and fried squid rings, served with a side of tangy marinara sauce for a classic appetizer experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Deviled Eggs",
                "description": "Classic deviled eggs, filled with a creamy and tangy yolk mixture, perfect for any occasion.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Caprese Salad",
                "description": "A refreshing salad of fresh mozzarella, ripe tomatoes, and basil, drizzled with olive oil and balsamic glaze.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Hummus",
                "description": "Smooth and creamy dip made from chickpeas blended with tahini, garlic, and lemon, served with pita bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Guacamole",
                "description": "A savory dip of ripe avocados mashed with lime, tomatoes, onions, and cilantro, perfect with tortilla chips.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Quesadillas",
                "description": "Grilled flour tortillas stuffed with melted cheese and your choice of additional fillings, served with salsa.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Cheese Platter",
                "description": "An assorted selection of gourmet cheeses, paired with crackers and fruit, perfect for sharing.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Main Courses": [
            {
                "name": "Grilled Chicken",
                "description": "Tender chicken breasts marinated in a blend of herbs and spices, grilled to juicy perfection, and served with a side of seasonal vegetables.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Beef Steak",
                "description": "Savor the richness of a thick, juicy steak grilled to your liking, featuring a flavorful crust and a tender, succulent interior, accompanied by a side of roasted potatoes.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Spaghetti Carbonara",
                "description": "Classic Italian pasta dish made with spaghetti tossed in a creamy sauce of eggs, cheese, pancetta, and pepper for a rich and comforting meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Salmon Fillet",
                "description": "Delicate salmon fillet grilled to perfection, infused with fresh herbs and lemon, served with a side of steamed asparagus.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Vegetarian Pizza",
                "description": "Artisan pizza topped with a colorful medley of fresh and roasted vegetables, melted mozzarella cheese, and a zesty tomato sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lamb Chops",
                "description": "Succulent lamb chops grilled to perfection, seasoned with rosemary and garlic, and served with a side of minty yogurt sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Chicken Alfredo",
                "description": "Tender pieces of chicken tossed with fettuccine pasta in a rich and creamy Alfredo sauce, topped with Parmesan cheese and fresh parsley.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Tofu Stir-fry",
                "description": "A vibrant and flavorful stir-fry featuring crispy tofu and a colorful array of fresh vegetables, tossed in a savory Asian-inspired sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Beef Tacos",
                "description": "Soft corn tortillas filled with seasoned and juicy beef, topped with fresh lettuce, tomatoes, cheese, and a drizzle of salsa.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Vegan Burger",
                "description": "A delectable plant-based patty served on a toasted bun with lettuce, tomato, onions, and your choice of vegan condiments, perfect for a guilt-free indulgence.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Lasagna",
                "description": "Hearty layers of pasta, rich meat sauce, creamy béchamel, and melted cheese baked to perfection for an Italian delight.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Chicken Curry",
                "description": "Aromatic and spicy Indian curry with tender chicken pieces simmered in a flavorful sauce, served with basmati rice or naan bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Ratatouille",
                "description": "A classic French vegetable stew featuring a harmonious blend of zucchini, bell peppers, eggplant, and tomatoes, slow-cooked with herbs for a wholesome meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Fish and Chips",
                "description": "Crispy battered fish fillets served with golden fries and a side of tangy tartar sauce, perfect for a satisfying meal by the sea.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Shrimp Scampi",
                "description": "Succulent shrimp sautéed in a rich garlic and butter sauce, served over linguine pasta with a hint of lemon.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Desserts": [
            {
                "name": "Chocolate Cake",
                "description": "Indulge in a decadent chocolate cake layered with rich chocolate ganache and topped with a velvety chocolate frosting for the ultimate chocolate lover's dream.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Cheesecake",
                "description": "Creamy and smooth cheesecake with a buttery graham cracker crust, topped with your choice of fresh berries or a fruit compote for a delightful finish.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Apple Pie",
                "description": "A timeless classic featuring tender slices of spiced apples encased in a flaky, golden crust, served warm with a scoop of vanilla ice cream.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Tiramisu",
                "description": "A luxurious Italian dessert layered with coffee-soaked ladyfingers, mascarpone cheese, and dusted with cocoa powder for a delightful treat.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Panna Cotta",
                "description": "A silky smooth Italian dessert made of sweetened cream and vanilla, set to perfection and garnished with a berry coulis.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Profiteroles",
                "description": "Delicate puff pastries filled with rich crème patissière and drizzled with a luscious chocolate sauce for an irresistible treat.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Creme Brulee",
                "description": "A classic French dessert featuring a creamy vanilla custard base topped with a perfectly caramelized sugar crust for a delightful crunch.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Brownie",
                "description": "Enjoy a classic chocolate brownie with a gooey center and a chewy crust, served warm and perfect with a dollop of ice cream.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Ice Cream",
                "description": "Scoop into a refreshing selection of assorted ice cream flavors, creamy and delicious with a variety of toppings available.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mousse",
                "description": "Savor a light and fluffy chocolate mousse, handcrafted with premium cocoa and topped with a dollop of whipped cream.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Fruit Tart",
                "description": "A delightful tart shell filled with creamy custard and adorned with an array of fresh seasonal fruits for a burst of natural sweetness.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Macarons",
                "description": "Enjoy delicate French almond cookies with a crisp shell and soft interior, available in a variety of delectable flavors.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Trifle",
                "description": "A layered dessert combining sponge cake, custard, fresh fruit, and whipped cream for a delightful balance of flavors and textures.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Lemon Meringue Pie",
                "description": "A tangy lemon pie crowned with fluffy meringue peaks, perfectly balancing sweet and sour flavors for a refreshing dessert.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Pavlova",
                "description": "A meringue-based dessert with a crisp crust and soft interior, topped with whipped cream and fresh fruit for a heavenly finish.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Salads": [
            {
                "name": "Caesar Salad",
                "description": "Crisp romaine lettuce tossed in a creamy Caesar dressing with crunchy croutons and shaved Parmesan cheese.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Greek Salad",
                "description": "A refreshing salad made with ripe tomatoes, crisp cucumbers, tangy feta cheese, and briny olives, drizzled with olive oil and oregano.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Caprese Salad",
                "description": "A simple and elegant salad featuring juicy tomatoes, creamy mozzarella cheese, and fresh basil leaves, drizzled with balsamic glaze.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Cobb Salad",
                "description": "A hearty salad with mixed greens, hard-boiled eggs, crispy bacon, avocados, tomatoes, and crumbled blue cheese, served with a vinaigrette.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Waldorf Salad",
                "description": "A delightful combination of crisp apples, grapes, and crunchy walnuts, tossed in a light and creamy dressing.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Spinach Salad",
                "description": "Fresh baby spinach leaves paired with crispy bacon bits, sliced mushrooms, and hard-boiled eggs, topped with a warm bacon dressing.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Quinoa Salad",
                "description": "Nutritious quinoa mixed with colorful vegetables and herbs, tossed in a zesty lemon vinaigrette for a refreshing taste.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Asian Slaw",
                "description": "A crunchy blend of cabbage, carrots, and bell peppers, dressed in a savory and tangy Asian-inspired dressing.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Kale Salad",
                "description": "Nutrient-rich kale leaves mixed with dried cranberries, toasted almonds, and a citrusy vinaigrette for a burst of flavor.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Pasta Salad",
                "description": "Fusilli pasta tossed with a mix of fresh vegetables, olives, and a tangy Italian dressing for a delicious and satisfying salad.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Broccoli Salad",
                "description": "Crunchy broccoli florets combined with crispy bacon, sweet raisins, and a creamy dressing for a tasty and textured salad.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Chickpea Salad",
                "description": "Protein-packed chickpeas mixed with cucumbers, tomatoes, onions, and fresh herbs, tossed in a light lemon dressing.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Tabbouleh",
                "description": "A fresh and vibrant salad made with finely chopped parsley, bulgur wheat, tomatoes, mint, and lemon juice.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Avocado Salad",
                "description": "Creamy avocado slices paired with mixed greens, cherry tomatoes, and a tangy lime dressing for a refreshing taste.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Fruit Salad",
                "description": "A colorful medley of fresh seasonal fruits, offering a natural sweetness and a burst of refreshing flavors.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Soups": [
            {
                "name": "Tomato Soup",
                "description": "A classic, smooth, and creamy tomato soup, seasoned with herbs and a hint of garlic, perfect for a comforting meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Chicken Noodle Soup",
                "description": "Hearty and soothing chicken broth filled with tender pieces of chicken, egg noodles, and a medley of vegetables.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Minestrone",
                "description": "A robust and healthy Italian vegetable soup loaded with beans, pasta, and seasonal vegetables in a savory tomato broth.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "French Onion Soup",
                "description": "Rich and flavorful soup made with caramelized onions in a beef broth, topped with melted cheese over a crispy bread slice.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Lentil Soup",
                "description": "A thick and nourishing soup made with tender lentils, vegetables, and aromatic spices for a wholesome experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Clam Chowder",
                "description": "A creamy and savory seafood soup rich with tender clams, potatoes, and onions, offering a taste of the sea.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Miso Soup",
                "description": "A delicate and savory Japanese soup made with fermented soy miso, tofu, seaweed, and spring onions, perfect to start any meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Pumpkin Soup",
                "description": "A velvety and creamy pumpkin soup infused with nutmeg and cinnamon, topped with a drizzle of cream and roasted seeds.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Gazpacho",
                "description": "A refreshing cold Spanish soup made with a blend of ripe tomatoes, cucumbers, and bell peppers, seasoned with olive oil and vinegar.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Carrot Ginger Soup",
                "description": "A smooth and slightly spicy soup combining the sweetness of carrots with the zing of fresh ginger for a delightful warmth.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Broccoli Cheddar Soup",
                "description": "A rich and creamy soup with tender broccoli florets and sharp cheddar cheese, creating a warm and cheesy delight.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Beef Stew",
                "description": "A hearty and warming stew with tender chunks of beef, potatoes, and carrots simmered in a rich and savory broth.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Split Pea Soup",
                "description": "A comforting and hearty soup made of split peas simmered to perfection with smoked ham and a blend of seasonings.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Turkey Soup",
                "description": "A delicious post-holiday soup crafted from turkey leftovers, vegetables, and wild rice, simmered in a savory broth.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Vichyssoise",
                "description": "A classic French cold soup made with pureed leeks and potatoes, enriched with cream and a hint of chives.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Side Dishes": [
            {
                "name": "Mashed Potatoes",
                "description": "Creamy and buttery mashed potatoes whipped to perfection and seasoned with a touch of garlic and herbs for extra flavor.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "French Fries",
                "description": "Golden and crispy potato fries, perfectly seasoned and served hot, making them a classic and irresistible side.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Onion Rings",
                "description": "Crunchy battered onion rings, fried to a golden brown and served with a side of tangy dipping sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Coleslaw",
                "description": "A refreshing and crisp cabbage and carrot slaw, mixed with a creamy and tangy dressing for a perfect balance.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Cornbread",
                "description": "Moist and tender traditional cornbread, with a hint of sweetness and a delightful crumbly texture.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Garlic Butter Potatoes",
                "description": "Oven-roasted potatoes drizzled with rich garlic butter and herbs, offering a savory and fragrant side dish.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Grilled Vegetables",
                "description": "A medley of seasonal vegetables, char-grilled to enhance their natural sweetness and flavor, served with a drizzle of balsamic glaze.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Rice Pilaf",
                "description": "A fragrant rice dish cooked with a blend of savory spices and vegetables, providing a perfect accompaniment to any meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Baked Beans",
                "description": "Rich and hearty beans slow-cooked in a sweet and smoky sauce, offering a classic and comforting taste.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Roasted Brussels Sprouts",
                "description": "Crispy and caramelized Brussels sprouts roasted to perfection, seasoned with olive oil and a sprinkle of sea salt.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Macaroni and Cheese",
                "description": "A creamy and cheesy pasta dish, featuring tender macaroni coated in rich cheddar cheese sauce, baked with a golden crust.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Stuffing",
                "description": "A flavorful bread-based stuffing mixed with aromatic herbs, spices, and vegetables, perfect for pairing with poultry dishes.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Potato Gratin",
                "description": "Thinly sliced potatoes layered in a creamy sauce and baked to a golden brown, offering a deliciously rich and comforting dish.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Steamed Asparagus",
                "description": "Tender green asparagus, lightly steamed to retain its vibrant color and crisp texture, seasoned with a hint of lemon.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Sautéed Spinach",
                "description": "Fresh spinach lightly sautéed with garlic and olive oil for a simple and nutritious side dish bursting with flavor.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Sandwiches": [
            {
                "name": "Club Sandwich",
                "description": "A hearty three-layered sandwich with turkey, bacon, lettuce, tomato, and mayonnaise, all packed between toasted slices of bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "BLT",
                "description": "A classic sandwich featuring crispy bacon, fresh lettuce, and ripe tomato, served on toasted bread with a spread of mayonnaise.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Grilled Cheese",
                "description": "The ultimate comfort food with gooey melted cheese between two slices of perfectly toasted bread, golden and crispy.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Chicken Wrap",
                "description": "Tender grilled chicken, fresh greens, and a touch of creamy dressing rolled inside a soft flatbread for a satisfying meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Reuben",
                "description": "A savory sandwich with corned beef, tangy sauerkraut, Swiss cheese, and Russian dressing, grilled between slices of rye bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Peanut Butter & Jelly",
                "description": "A beloved classic combining creamy peanut butter and sweet jelly spread between soft slices of bread for a sweet treat.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Turkey and Swiss",
                "description": "Slices of roast turkey and Swiss cheese combined with lettuce and mayonnaise, served on your choice of bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Egg Salad Sandwich",
                "description": "Creamy egg salad mixed with a hint of mustard, sandwiched between fresh slices of bread for a quick and satisfying meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Ham and Cheese",
                "description": "Classic and satisfying, with sliced ham and melted cheese layered between two slices of warm, toasted bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Falafel Pita",
                "description": "Crispy falafel balls, fresh lettuce, tomatoes, and tangy tahini sauce, all tucked inside a warm pita bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Tuna Melt",
                "description": "Hearty tuna salad topped with melted cheese, served open-faced or between slices of grilled bread for a comforting meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Vegan Wrap",
                "description": "A colorful wrap filled with creamy hummus, fresh vegetables, and sprouts, all rolled up in a soft tortilla.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Cuban Sandwich",
                "description": "A flavorful combination of ham, roasted pork, Swiss cheese, pickles, and mustard pressed to perfection on Cuban bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Roast Beef Sandwich",
                "description": "Slices of tender roast beef and sharp cheddar cheese layered with fresh lettuce and horseradish mayo on a crusty roll.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Caprese Sandwich",
                "description": "Fresh mozzarella, ripe tomatoes, and basil leaves, drizzled with balsamic glaze, all nestled in a rustic baguette.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Seafood": [
            {
                "name": "Grilled Shrimp",
                "description": "Juicy shrimp marinated with herbs and spices, grilled to perfection, and served with a side of lemon garlic butter.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Crab Cakes",
                "description": "Golden cakes made with fresh crab meat, seasoned with a blend of spices, and served with a zesty remoulade sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lobster Tail",
                "description": "Succulent broiled lobster tail drizzled with lemon butter, offering a rich and luxurious seafood experience.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Fish Tacos",
                "description": "Crispy fish fillets nestled in warm tortillas, topped with fresh slaw and a tangy lime sauce for a perfect bite.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Seafood Paella",
                "description": "A vibrant and flavorful Spanish dish with mixed seafood, saffron-infused rice, and assorted vegetables.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Oysters on the Half Shell",
                "description": "Fresh, raw oysters served chilled with a side of tangy mignonette and lemon wedges.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mussels in White Wine Sauce",
                "description": "Tender mussels cooked in a fragrant white wine garlic sauce, served with crusty bread for dipping.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Grilled Octopus",
                "description": "Tender octopus grilled to perfection, seasoned with olive oil and herbs, served with a side of roasted potatoes.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Fried Fish",
                "description": "Classic battered fish, fried until golden and crispy, served with tartar sauce and a lemon wedge.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Blackened Catfish",
                "description": "Spicy and flavorful catfish fillet, expertly blackened on a hot grill, served with a side of coleslaw.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Seafood Gumbo",
                "description": "A rich and hearty stew with shrimp, crab, andouille sausage, and okra, simmered in a flavorful roux-based broth.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Baked Salmon",
                "description": "Oven-baked salmon fillet, seasoned with herbs and citrus, served with a side of steamed vegetables.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Sushi Rolls",
                "description": "A delightful assortment of sushi rolls, including fresh fish, vegetables, and vinegared rice, expertly rolled and served with soy sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Tuna Sashimi",
                "description": "Fresh slices of raw tuna, expertly cut and served with soy sauce and a hint of wasabi.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Scampi",
                "description": "Succulent prawns sautéed in a rich garlic butter sauce with parsley and lemon, served over pasta or with crusty bread.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
        "Vegetarian": [
            {
                "name": "Vegetable Stir-fry",
                "description": "A vibrant medley of fresh vegetables, wok-tossed with a savory and slightly sweet sauce, served with steamed rice or noodles.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Vegetarian Curry",
                "description": "A rich and flavorful curry filled with a variety of mixed vegetables, simmered in aromatic spices and coconut milk for a satisfying meal.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Veggie Burger",
                "description": "A delicious grilled veggie patty made with a blend of beans, grains, and spices, served on a bun with fresh lettuce, tomato, and avocado.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Mushroom Risotto",
                "description": "Creamy arborio rice cooked slowly with earthy mushrooms and Parmesan cheese, finished with a hint of truffle oil.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Stuffed Bell Peppers",
                "description": "Colorful bell peppers stuffed with a protein-rich mixture of quinoa, vegetables, and herbs, baked until tender.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Eggplant Parmesan",
                "description": "Layers of breaded eggplant, marinara sauce, and melted mozzarella cheese, baked until bubbly and golden.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Vegetable Lasagna",
                "description": "A comforting lasagna filled with layers of pasta, assorted roasted vegetables, rich marinara, and creamy béchamel sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Chickpea Salad",
                "description": "A refreshing salad with spiced chickpeas, fresh greens, cherry tomatoes, cucumber, and a lemon-tahini dressing.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Falafel",
                "description": "Crispy and golden fried chickpea balls, seasoned with herbs and spices, served with a side of hummus or in a warm pita.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Veggie Tacos",
                "description": "Soft corn tortillas filled with an assortment of seasoned vegetables, topped with salsa, avocado, and fresh cilantro.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Paneer Butter Masala",
                "description": "Soft paneer cubes simmered in a rich, creamy, and spicy tomato-based sauce, served with rice or naan.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Spinach and Ricotta Ravioli",
                "description": "Delicate pasta pockets stuffed with a creamy spinach and ricotta filling, topped with a light tomato and basil sauce.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
            {
                "name": "Vegetable Quesadillas",
                "description": "Crispy tortillas filled with melted cheese and mixed vegetables, served with salsa and sour cream on the side.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[0],
            },
            {
                "name": "Vegan Sushi",
                "description": "Flavorful rolls filled with a variety of fresh vegetables and avocado, wrapped in seasoned rice and nori.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[1],
            },
            {
                "name": "Lentil Burgers",
                "description": "Savory lentil patties grilled to perfection, served on a whole grain bun with lettuce, tomato, and vegan mayo.",
                "image": "300x300-Placeholder-Image.jpg",
                "restaurant": restaurants[2],
            },
        ],
    }

    for category in categories:
        product_list = products_data.get(category.name, [])
        for product_data in product_list:
            product_model.objects.create(
                name=product_data["name"],
                description=product_data["description"],
                category=category,
                restaurant=product_data["restaurant"],
                image=product_data["image"],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("online_delivery", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
